import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Image from "next/image"
import { MainNav } from "./components/MainNav";
import { UserNav } from "./components/UserNav";
import { ModeToggle } from "@/components/ModeToggle";
import { au } from '@/auth';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            
          <main className="max-w-6xl mx-auto px-4">

            <div className="md:hidden">
              <Image
                src="/examples/dashboard-light.png"
                width={1280}
                height={866}
                alt="Dashboard"
                className="block dark:hidden"
              />
              <Image
                src="/examples/dashboard-dark.png"
                width={1280}
                height={866}
                alt="Dashboard"
                className="hidden dark:block"
              />
            </div>
            <div className="hidden flex-col md:flex">
              <div className="border-b py-5">
                <div className="flex items-center">
                  <MainNav className="" />
                  
                  <div className="ml-auto flex items-center space-x-4">
                  <ModeToggle />
                    <UserNav />
                  </div>
                  
                </div>
              </div>
              <div className="flex-1 space-y-4 pt-6">
                {children}
              </div>
            </div>

          </main>


          </ThemeProvider>
      </body>
    </html>
  );
}
